### ISSUE TITLE
ROS Noetic binary package not available

### ISSUE THREAD

**Issue by kbrameld** [mikeferguson/simple_grasping#10]
The noetic binary job seems to be [failing](https://build.ros.org/job/Nbin_db_dB64__simple_grasping__debian_buster_amd64__binary/775/console#console-section-12) on the buildfarm, and due to that the package can't be installed via ``apt``:

```
apt install ros-noetic-simple-grasping
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-noetic-simple-grasping
```

The issue sounds very similar to https://github.com/ros/rosdistro/issues/25233

**Comment by mikeferguson** [comment]
Interesting - I'm not sure why I haven't been getting the build failure emails....

**Comment by mikeferguson** [comment]
#11 should fix this - cutting a new release now

**Comment by mikeferguson** [comment]
https://github.com/ros/rosdistro/pull/36934

**Comment by kbrameld** [comment]
Thanks @mikeferguson !
