### ISSUE TITLE
ROS2 Foxy build fails

### ISSUE THREAD

**Issue by 130s** [mikeferguson/simple_grasping#12]
# Issue
I assume `foxy` is not targeted having seen https://github.com/mikeferguson/simple_grasping/pull/9 merged into `ros2` branch. But in case anyone is wondering, build on foxy fails due to the changes added in that PR.

**Comment by 130s** [comment]
I have working code in https://github.com/130s/simple_grasping/pull/1. I can open a PR once I clean it up.

**Comment by 130s** [comment]
> I have working code in [130s#1](https://github.com/130s/simple_grasping/pull/1). I can open a PR once I clean it up.

I mean I won't try to get a single branch work for both 20.04 and 22.04. So no, I will unlikely open a PR to address this ticket. Since I tentatively need Foxy and Galactic, I am maintaining <s>`foxy-devel`</s> [`galactic-devel`](https://github.com/130s/simple_grasping/tree/galactic-devel) branch on my fork (for now).

**Comment by mikeferguson** [comment]
Foxy is now EOL
