### ISSUE TITLE
Citation for the package

### ISSUE THREAD

**Issue by jontromanab** [mikeferguson/simple_grasping#2]
Hello Michael,

I don't know it is the proper place or not. But I have not got any other way to contact you. I have developed a new grasp planner package for grasping with multi DOF joint hands such as Barrett hand and Robotiq Gripper. I have implemented the package for a robot with UR5 arm and Barrett hand. My package is highly influenced by the simple_grasping package  especially calling the bounding box for objects (Though I have developed it for sphere also as well as box and cylinder, as asked in your package) and calling moveit through the grasps.

I am planning to submit a draft a IROS2016, where I want to cite the package "simple_grasping". Would you please let me know how I can cite this package?? [The deadline for submitting is 1st of March, Though it is quite near, I still cannot submit it without citing your package]

Thank you very much. Please help me.

**Comment by mikeferguson** [comment]
There isn't a paper or whatnot for this package, so I suppose the best way is to cite similar to what MoveIt recommends:

Michael Ferguson, "The simple_grasping ROS package", [Online] Available: https://github.com/mikeferguson/simple_grasping

**Comment by jontromanab** [comment]
Thank you very much.

On Sun, Feb 28, 2016 at 11:43 AM, Michael Ferguson <notifications@github.com
> wrote:

> There isn't a paper or whatnot for this package, so I suppose the best way
> is to cite similar to what MoveIt recommends:
>
> Michael Ferguson, "The simple_grasping ROS package", [Online] Available:
> https://github.com/mikeferguson/simple_grasping
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikeferguson/simple_grasping/issues/2#issuecomment-189921120>
> .
>



-- 
Abhijit Makhal
Robotics and Artificial Intelligence Lab
Indian Institute of Information Technology
