### ISSUE TITLE
grasping_msgs Dependencies not well set up

### ISSUE THREAD

**Issue by RDaneelOlivav** [mikeferguson/simple_grasping#5]
simple_grasping/include/simple_grasping/object_support_segmentation.h:36:10: fatal error: grasping_msgs/Object.h: No such file or directory
 #include <grasping_msgs/Object.h>

It seems that there is something in the CMakeLists.txt that should be corrected? 
Can someone tell me how to fix this so that catkin_make without having to first compile grasping_msgs and then the rest?

**Comment by mikeferguson** [comment]
Both the CMake and package.xml call out grasping messages (and things are passing on CI and debs are building...) -- so I'm not sure why it isn't working for you.

**Comment by RDaneelOlivav** [comment]
I know, its strange right? I mean when compiled the messages before and then we compile the rest , it works. It seems as if it doesnt seem to get that he has to compile the msgs firts to have it
